  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      networks:
        - elastic
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200/
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
        - elasticsearch
      networks:
        - elastic

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks:
        - elastic

    elasticsearch-hq:
      image: elastichq/elasticsearch-hq
      container_name: elasticsearch-hq
      ports:
        - 5000:5000
      networks:
        - elastic

  volumes:
    data:
      driver: local

  networks:
    elastic: