# Generated by Django 2.2.3 on 2020-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.TextField()),
                ('short_title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('rooms_count', models.IntegerField()),
                ('url', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('price_hr', models.IntegerField(blank=True, null=True)),
                ('price_usd', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
