# Generated by Django 2.2.3 on 2019-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_advertisement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
