# Generated by Django 2.2.3 on 2019-07-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190718_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
