# Generated by Django 2.2.3 on 2019-07-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20190719_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='price_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
